### ISSUE TITLE
Add BaseTransaction implementation

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-elements#874]
### Description
Currently in elements it only supports creation of the transaction, but it should add all the features related to the transaction.
Also, developer should be able to easily extend the BaseTransaction to create new type of transaction.

- validate
- verify
- apply
- undo
- create
- verifyAgainstTransactions

### Child issues
- [x] create draft implementation
- [x] Add Base Transaction `checkSchema` #941 
- [x] Add Base Transaction `checkTypes` #944 
- [x] Add Base Transaction `validate` #942
- [x] Add Base Transaction `apply` #945 
- [x] Add Base Transaction `undo` #946 
- [x] Add Base Transaction `isExpired` #947
